<?php

return [

    /*
     * The default genders (keys/values) that will be used.
     */
    'default' => [
        'male' => 'Male',
        'female' => 'Female',
    ],

    /*
     * Other genders (keys/values) that can be included via includeExtended().
     *
     * Source: https://www.telegraph.co.uk/technology/facebook/10930654/Facebooks-71-gender-options-come-to-UK-users.html
     */
    'extended' => [
        'agender' => 'Agender',
        'androgyne' => 'Androgyne',
        'androgynes' => 'Androgynes',
        'androgynous' => 'Androgynous',
        'asexual' => 'Asexual',
        'bigender' => 'Bigender',
        'cis' => 'Cis',
        'cis-female' => 'Cis Female',
        'cis-male' => 'Cis Male',
        'cis-man' => 'Cis Man',
        'cis-woman' => 'Cis Woman',
        'cisgender' => 'Cisgender',
        'cisgender-female' => 'Cisgender Female',
        'cisgender-male' => 'Cisgender Male',
        'cisgender-man' => 'Cisgender Man',
        'cisgender-woman' => 'Cisgender Woman',
        'f2m' => 'F2M',
        'female-to-male' => 'Female to Male',
        'female-to-male-trans-man' => 'Female to male trans man',
        'female-to-male-transgender-man' => 'Female to male transgender man',
        'female-to-male-transsexual-man' => 'Female to male transsexual man',
        'ftm' => 'FTM',
        'gender-fluid' => 'Gender Fluid',
        'gender-neutral' => 'Gender neutral',
        'gender-nonconforming' => 'Gender Nonconforming',
        'gender-questioning' => 'Gender Questioning',
        'gender-variant' => 'Gender Variant',
        'genderqueer' => 'Genderqueer',
        'hermaphrodite' => 'Hermaphrodite',
        'intersex' => 'Intersex',
        'intersex-man' => 'Intersex man',
        'intersex-person' => 'Intersex person',
        'intersex-woman' => 'Intersex woman',
        'm2f' => 'M2F',
        'male-to-female' => 'Male to Female',
        'male-to-female-trans-woman' => 'Male to female trans woman',
        'male-to-female-transgender-woman' => 'Male to female transgender woman',
        'male-to-female-transsexual-woman' => 'Male to female transsexual woman',
        'man' => 'Man',
        'mtf' => 'MTF',
        'neither' => 'Neither',
        'neutrois' => 'Neutrois',
        'non-binary' => 'Non-binary',
        'other' => 'Other',
        'pangender' => 'Pangender',
        'polygender' => 'Polygender',
        't*man' => 'T* man',
        't*woman' => 'T* woman',
        'trans' => 'Trans',
        'trans-female' => 'Trans Female',
        'trans-male' => 'Trans Male',
        'trans-man' => 'Trans Man',
        'trans-person' => 'Trans Person',
        'trans*female' => 'Trans*Female',
        'trans*male' => 'Trans*Male',
        'trans*man' => 'Trans*Man',
        'trans*person' => 'Trans*Person',
        'trans*woman' => 'Trans*Woman',
        'transexual' => 'Transexual',
        'transexual-female' => 'Transexual Female',
        'transexual-male' => 'Transexual Male',
        'transexual-man' => 'Transexual Man',
        'transexual-person' => 'Transexual Person',
        'transexual-woman' => 'Transexual Woman',
        'transgender-female' => 'Transgender Female',
        'transgender-person' => 'Transgender Person',
        'transmasculine' => 'Transmasculine',
        'two*person' => 'Two* person',
        'two-spirit' => 'Two-spirit',
        'two-spirit-person' => 'Two-spirit person',
        'woman' => 'Woman',
        'decline' => 'Prefer not to say',
    ],
];
